### ISSUE TITLE
error: Cannot resolve module typeorm

### ISSUE THREAD

**Issue by lapwat** [denolib/typeorm#55]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest (0.2.23-rc3)`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

When copying install instruction from the readme:

```sh
$ deno install --allow-read --allow-write --allow-net --allow-env -f typeorm https://denolib.com/denolib/typeorm@v0.2.23-rc3/cli.ts
error: Cannot resolve module "file:///home/dev/typeorm"
```

**Comment by zhmushan** [comment]
try `deno install --unstable --allow-read --allow-write --allow-net --allow-env -f -n typeorm https://denolib.com/denolib/typeorm/cli.ts`

In deno1.0, we need to use `-n` to specify the script name

**Comment by tezine** [comment]
> try `deno install --unstable --allow-read --allow-write --allow-net --allow-env -f -n typeorm https://denolib.com/denolib/typeorm/cli.ts`
> 
> In deno1.0, we need to use `-n` to specify the script name

I tried to execute with these parameters, but I get the error below:
```bash
...
Download https://denolib.com/denolib/typeorm/src/driver/sap/SapDriver.ts
error: error sending request for url (https://denolib.com/denolib/typeorm/src/decorator/options/JoinColumnOptions.ts): http2 error: protocol error: not a result of an error
```

**Comment by lapwat** [comment]
This command failed:
```sh
$ deno install --unstable --allow-read --allow-write --allow-net --allow-env -f -n typeorm https://denolib.com/denolib/typeorm@v0.2.23-rc3/cli.ts
...
Download https://denolib.com/denolib/typeorm@v0.2.23-rc3/src/commands/CommandUtils.ts
error: TS2322 [ERROR]: Type 'string' is not assignable to type 'boolean'.
  return srcArray.reduce(
  
    at https://deno.land/std@v0.42.0/fs/utils.ts:20:3

TS2305 [ERROR]: Module '"./types/AutoSavable"' has no exported member 'AutoSavable'.
import type { AutoSavable, AutoSavableDriver } from "./types/AutoSavable.ts";
              ~~~~~~~~~~~
    at https://denolib.com/denolib/typeorm@v0.2.23-rc3/src/driver/DriverUtils.ts:3:15

Found 2 errors.
```

But the one you gave worked!

```sh
$ deno install --unstable --allow-read --allow-write --allow-net --allow-env -f -n typeorm https://denolib.com/denolib/typeorm/cli.ts
...
Download https://unpkg.com/cac@6.5.9/mod.js
✅ Successfully installed typeorm
```

Thanks!

**Comment by lapwat** [comment]
Please @tezine open a new issue because I will close this one :)

**Comment by tezine** [comment]
Thank you @lapwat . It's not working yet. Sometimes I receive a message indicating `broken pipe` and sometimes  `http2 error: protocol error: not a result of an error`. My connection is stable. I think this is not related to TypeOrm, but how Deno is handling the connection. Thank you anyway!
