### ISSUE TITLE
[documentation] Add installation command for deno v1.0

### ISSUE THREAD

**Issue by lapwat** [denolib/typeorm#56]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

#55 The installation command in the readme does not work for deno v1.0.

This one works:

```sh
deno install --unstable --allow-read --allow-write --allow-net --allow-env -f -n typeorm https://denolib.com/denolib/typeorm/cli.ts
```

**Comment by uki00a** [comment]
@lapwat 
I've fixed README.md at #58.
Thanks for reporting this!
