### ISSUE TITLE
Bump Deno SQLite to 2.0.0

### ISSUE THREAD

**Issue by dyedgreen** [denolib/typeorm#64]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Comment by uki00a** [comment]
I bumped deno-sqlite to v2.1.0 at #68.
Thanks @dyedgreen!
